pupa/utils/generic.py
What can I say - I like my periods.
Also, in Toronto, the removed line would cause collisions between `2011.CC11.1` and `2011.CC1.11`.
=> don't run Sunlight-specific bill identifier cleanup

pupa/cli/commands/update.py
forgot to use `format`, here.  it was just recording "{k}={v}", lol
=> proper report formatting of scraper params

pupa/cli/commands/update.py, pupa/importers/bills.py, pupa/importers/people.py, pupa/scrape/bill.py, pupa/tests/importers/test_bill_importer.py, pupa/tests/importers/test_vote_importer.py
These series of commits is here to solve #160 
The `BillImporter` has been changed to be aware of the `PersonImporter`. Existing interface code (I'm looking at you, `opencivicdata.org`) will need to change to match.
`limit_spec` for `PersonImporter` has been implemented with something suitably generic. Test-case is in place to test that.
I've added the original feature, as well - to resolve people by `identifiers.identifier`. I've credited @crdunwel on that commit, since it's his work (but faked the commit, sorry, Clay :+1: )
=> Allow pseudo IDs in the sponsor ID fields

pupa/cli/commands/update.py
`legislative_sessions` support on Jurisdiction is currently busted.
`check_session_list` requires a `_scraped_name` key, but this key is not removed before importing, causing LegislativeSession creation to fail. I think `get_session_list` should just return the real, actual name and forget about scraped names. If that method needs to have a hardcoded dictionary mapping the scraped names to the correct names, do it - it just means moving the hardcoding from the `legislative_sessions` array to the method, with the benefit that you don't need to muck around later popping `_scraped_name` off a deep-clone of the `legislative_sessions` list.
=> use name instead of _scraped_name for legislative sessions

requirements-test.txt
This should be the last of 'em.
=> Upgrade tests from Django 1.7 RC to 1.7 full, in line with the other OCD repos

pupa/cli/commands/update.py, pupa/importers/base.py, pupa/settings.py, pupa/utils/__init__.py, pupa/utils/generic.py
This will forward all pupa reports along on Kafka if doing an import.
This will solve #173 - also enables https://github.com/paultag/sunlight-scratch/blob/master/kafka-forward.py
Should settings-gate it out.
Reviews / ACKs? @rshorey @mileswwatkins @boblannon @apendleton
=> Experimental Kafka reporting

pupa/scrape/event.py
add_participant also accepts an ID argument in accordance with the spec for Event http://docs.opencivicdata.org/en/latest/proposals/0004.html#participants
=> convenience method for committee participation

pupa/cli/commands/dbinit.py, pupa/cli/commands/dump.py, pupa/cli/commands/init.py, pupa/exceptions.py, pupa/importers/base.py, pupa/importers/bills.py, pupa/importers/events.py, pupa/scrape/base.py, pupa/scrape/bill.py, pupa/scrape/popolo.py, pupa/tests/django_settings.py, pupa/tests/importers/test_base_importer.py, pupa/tests/importers/test_event_importer.py, pupa/tests/importers/test_membership_importer.py, pupa/tests/importers/test_organization_importer.py, pupa/tests/importers/test_people_importer.py, pupa/tests/importers/test_vote_importer.py, pupa/tests/scrape/test_bill_scrape.py, pupa/tests/scrape/test_event_scrape.py, pupa/utils/event.py, pupa/utils/generic.py, tox.ini
noticed this when working on the django 1.8 branch, a lot of noise here made keeping things flake8 hard
this leaves two flake8 errors both of which are interesting and possibly bugs
pupa/importers/memberships.py:43:9: F841 local variable 'party_flag' is assigned to but never used
pupa/importers/organizations.py:50:9: F841 local variable 'pseudo_children' is assigned to but never used
we should probably take a look at these two before just blindly fixing them
=> fix almost all flake8 errors

requirements-test.txt
pointing at an old version of pypi, shld probably fix pypi at some point but this quick fix will work.
=> pull ocd-django from github instead of pypi

pupa/importers/base.py
Right now if you have a person who is a member of "City Council" and "Committee on Finance" for that committee then: 
```python
self.model_class.objects.get(name='Jane Doe', 
memberships__organization__jurisdiction_id='ocdjurisdiction/country:us/state:ny/place:new_york/government').id
```
Fails with a `MultipleObjectsReturned` error. This is because the `memberships__organizations__jurisdiction_id` parameter will cause Django to return an object for **each** membership in an organization within a jurisdiction id. Since Jane Doe is both a member of the council and a committee and both are under the same jurisdiction, Jane's object will be returned twice.
This pull request handles that by allowing for multiple objects to be returned and then checking to make sure that there is one and only …
=> Allows resolutions of people with memberships in multiple sub jurisdiction organizations

pupa/scrape/popolo.py, pupa/tests/scrape/test_people_org_scrape.py
I know add_membership doesn't get used much, but I needed it for scraping LegistarOrganizationScraper when splitting the people scraper from the org scraper.
Much appreciated for considering the merge!
=> Org name resolution on Person.add_membership

setup.py
https://github.com/opencivicdata/pupa/blob/master/setup.py#L21
Right now, if I'm using a custom version of opencivicdata-django in my scrapers, I need to also use a custom pupa package in order for errors to not be thrown. Could we relax this to use `>=` rather than `==`?
=> Relax opencivicdata-django version constraint

setup.py
Was setting up the OCD environment on my current machine (macOS 10.12, Python 3.5). This PR addresses one hitch I hit while setting up the Pupa environment:
- `python setup.py install`ing Pupa in the virtualenv does install the Python Egg, however only as binary, not as an unzipped directory
- Django, when running `pupa dbinit ${your favorite country}`, expects `site-packages/pupa-${version}.egg` to _not_ be a binary, so that it can access the `pupa/migrations` inside it as a directory; otherwise, it throws a `NotADirectoryError`
- Re-`setup.py`ing Pupa after adding `zip_safe=False` to `setup()` makes everything work properly.
This could be my own misunderstanding of Python packaging, but I ran it by @jamesturk for a sanity check. Probably just a tiny issue with environment differences.
=> Force unpacking of Python egg, for accessible Django migrations

pupa/scrape/jurisdiction.py
This commit https://github.com/opencivicdata/pupa/commit/c54e8969f6dae1d3de364c31e5ee2a0cf0b69925#commitcomment-20440348 introduced a requirement that JurisdictionScraper classes have an attribute called `get_session_list`
This is a backwards incompatible change. 
I attempted to reverse this backwards incompatibility by allowing the attribute to not be defined in https://github.com/opencivicdata/pupa/commit/0b30407a634773d6e3bf8fbf07b683e10ef87c8d
However, this was not a sufficient fix because, [for a long time](https://github.com/opencivicdata/pupa/blame/master/pupa/scrape/jurisdiction.py#L45), `get_session_list` has been defined on the base `JurisdictionScraper` class.
So, unless it is explicitly deleted, then `get_session_list` always exists. And if it is not overridden in a derived …
=> template method for get_session_list

CHANGELOG.md, pupa/importers/memberships.py, pupa/scrape/popolo.py, pupa/scrape/schemas/membership.py, pupa/tests/importers/test_membership_importer.py, requirements-test.txt
see #253 
these tests won't pass on TravisCI until https://github.com/opencivicdata/python-opencivicdata-django/pull/75 is merged but do pass locally
=> relax person resolution in Membership and add person_name attribute

pupa/cli/__main__.py
As a developer, I want to be able to tack `--debug` onto the end of a command without wasting valuable ( 😉 ) seconds scrolling back to the beginning of the line.
This also (sort of) fixes an issue with the current `--debug` flag. As implemented, it takes zero arguments (use pdb) or one (use a custom debugger). But when it's passed to the main command instead of a subcommand, it effectively must take exactly one argument--otherwise, the subcommand will be interpreted as the argument to `--debug`. In other words, users can't do this:
```
pupa --debug update ny
```
If `--debug` is accepted by subcommands, as it is in this patch, users *can* do this:
```
pupa update ny --debug
```
Which is what I wanted to do in the first place. This patch still isn't perfect, since now `--debug` takes zero …
=> Add common args to subcommands.

pupa/importers/events.py
In a previous PR, I added `fix_bill_ids` to help with the resolution of bill ids as related entities of event agenda items. I didn't adequately handle the pseudo id nature of these ids. This fixes that.
=> handle pseudo ids in event importer of bill ids

CHANGELOG.md, pupa/importers/vote_events.py, pupa/scrape/schemas/vote_event.py, pupa/scrape/vote_event.py, pupa/tests/importers/test_vote_event_importer.py
allows setting a bill_action property when scraping VoteEvent, which will cue pupa to try to resolve to a BillAction on the same date/chamber w/ the same action text
depends on opencivicdata/python-opencivicdata-django#78
=> Related vote events

CHANGELOG.md, pupa/cli/commands/update.py, pupa/importers/jurisdiction.py
this is a bit of an odd case, lets this property be set at scrape time but not saved, will be used when session list checking occurs (useful in case the state's session identifiers are completely opaque, like internal DB ids)
=> _scraped_name

pupa/cli/commands/update.py, pupa/scrape/base.py, pupa/settings.py, pupa/tests/django_settings.py, pupa/tests/scrape/test_utils.py, run-tests.sh, tox.ini
Settings passed to scrapelib don't seem to do anything at the moment. This patch applies overrides from scraper modules and command-line arguments. Logic lifted from billy.
=> Override settings from modules and args.

pupa/scrape/event.py, pupa/scrape/schemas/event.py, pupa/tests/scrape/test_event_scrape.py, requirements-test.txt
This is reticketed from here https://github.com/opencivicdata/scrapers-ca/pull/168#issuecomment-173796717
Presumably I would start with a PR to [`opencivicdata/python-opencivicdata-django`](https://github.com/opencivicdata/python-opencivicdata-django/blob/master/opencivicdata/models/event.py), but it seemed to make most sense to ask for a blessing here first :)
Would adding a classification to agenda items be an acceptable approach?
=> Add classification field to EventAgendaItem

pupa/cli/__main__.py, pupa/cli/commands/base.py, pupa/cli/commands/init.py, pupa/cli/commands/update.py, pupa/exceptions.py, pupa/scrape/base.py, pupa/scrape/event.py, pupa/scrape/popolo.py, pupa/scrape/vote_event.py, pupa/tests/scrape/test_bill_scrape.py, pupa/tests/scrape/test_people_org_scrape.py, tox.ini
- consolidates a few places where exceptions were defined into pupa.exceptions
- the only real difference is that a lot of uses of bare ValueError are now ScrapeValueError (which does inherit from ValueError)- this makes future enhancements
hoping to lay some groundwork here for gradual improvement of error messages by catching most/all pupa-defined exceptions and printing useful error messages instead of stack traces
closes #114
=> consolidate exceptions a bit

pupa/importers/organizations.py, pupa/tests/importers/test_organization_importer.py, pupa/tests/scrape/test_people_org_scrape.py
The query for checking other names in `limit_spec` for orgs was missing a grouping paren. Now it follows same logic as `get_object`
=> fix query for other_names

CHANGELOG.md, pupa/scrape/vote_event.py, pupa/tests/scrape/test_vote_event_scrape.py
I'm a bit confused how we managed without this fix, but it appears that we don't currently add the legislative session ID to the VoteEvent.bill psuedo_id for resolution
we were getting errors like:
pupa.exceptions.UnresolvedIdError: multiple objects returned for Bill pseudo id ~{"from_organization__classification": "upper", "identifier": "SB 1"}: {'ocd-bill/4cebaa7a-087f-43ed-b5e8-ace698ddb5cf', 'ocd-bill/d79b9d92-d030-4e05-8fb3-4e9cf7830d99'}
But adding this causes legislative_session__identifier to be taken into account (set to the VoteEvent.legislative_session  and these votes resolve appropriately)
=> Fix voteevent bill session

setup.py
Lots of user warnings like this when running pupa in openstates:
```
/opt/openstates/venv-pupa/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: 
The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing 
from binary please use "pip install psycopg2-binary" instead. For details see: 
<http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
```
Docs: http://initd.org/psycopg/docs/install.html#binary-install-from-pypi
=> psycopg2 wheel is changing names

pupa/utils/topsort.py, setup.py
Looks like we're using jsonschema 3.x. This pins the install to use the latest version. We should drop the alpha release once a stable release is out.
=> Pin jsonschema to compatible version

pupa/scrape/__init__.py, pupa/scrape/vote_event.py, pupa/tests/scrape/test_vote_event_scrape.py
OpenStates `VoteEvent`s are often impossible to order within a given day, because chambers often provide the date of a vote without a time of day, and because the OCD `VoteEvent` definition does not provide an `order` field similar to `BillAction`.
This PR provides a scraper-based stopgap means of ordering votes, by adding an `order` value in seconds to `start_date` and `end_date`, when they have no time-of-day component.  A scraper creates a single instance of `OrderVoteEvent` (herein) and then passing each VoteEvent through it before emitting. 
When and if an "order" value is added to VoteEvent, it could be filled by this as well.  I'll start on that shortly and see how it goes.
This has been tested _in situ_ with only a single state, New Hampshire, but I hope and believe the usage …
=> Apply order to VoteEvents.

pupa/scrape/base.py, pupa/scrape/event.py, pupa/scrape/schemas/common.py, pupa/scrape/schemas/event.py
This PR closes #324 by allowing a date to be set on `add_media_link` and `add_document` methods of the Event scraper class.
This doesn't come with tests, but it doesn't quite feel like it needs tests since the underlying _add_associated_link method is already tested. 
I've also fixed up the schema for fuzzy_date_blank which had a bad regex and which also permitted datetimes. This does seem like something that we might want to test, but we don't have any tests for schemas that I could find.
Please advise @jamesturk .
=> Set date on event documents and event media links

pupa/scrape/jurisdiction.py
This PR changes `default_scrapers` from an empty dictionary to None on the base Jurisdiction class. 
I made this change to restore fallback behavior for bare `pupa update` commands, i.e., run all scrapers if no defaults are defined. This seems to be the intention of the code, however 
because `default_scrapers` is defined as an empty dict, bare commands fall into the second conditional block (`default_scrapers` is not None), rather than the final `else` block.
https://github.com/opencivicdata/pupa/blob/ab0fa5d9a5912d0347bdc1d67e854920b8a46c3d/pupa/cli/commands/update.py#L280-L307
Thank you so much for all your hard work on `pupa`! 🐛
=> Run all scrapers on pupa update if no defaults defined

pupa/importers/people.py, pupa/tests/importers/test_people_importer.py
Some entities that need people resolution (primarily bill actions) will frequently have last names only, and not a full name. Since we might have a family name for a person, attempt to use this as well when resolving a person.
See https://github.com/openstates/openstates/issues/3102. This might not be helpful with common last names (e.g. Smith), so perhaps a more complex logic for those cases would be better (matching legislator start/end dates to vote dates?).
=> Use family name when resolving person entities

pupa/importers/base.py
This PR adds a line to save new objects after related objects are created. This allows use of [Django's `post_save` signal](https://docs.djangoproject.com/en/2.2/ref/signals/#post-save) to perform operations that depend on related objects. 
Take our use case as an example: We want to [use some custom logic](https://github.com/datamade/django-councilmatic/pull/264) to determine a bill's last action date. This logic depends on two types of related objects, bill actions and event related entities. The change in this PR allows us to query related objects after `Event` and `Bill` save in order to determine the appropriate last action date.
As ever, thanks for your work!
=> Add support for post-save signals that depend on related objects

.gitignore, pupa/importers/events.py, pupa/scrape/event.py, pupa/scrape/schemas/event.py, pupa/tests/importers/test_event_importer.py, pupa/tests/scrape/test_event_scrape.py
sometimes events don't have physical locations (like remote meetings). this makes "location_name" an optional arg for the Event class
=> make location_name optional

pupa/importers/memberships.py, pupa/tests/importers/test_membership_importer.py
This PR updates the membership import spec, such that if a membership has a start date, `pupa` will use it to resolve the incoming membership with an existing membership. Otherwise, it will fall back to end date, which was the original default, preserved here to handle historic memberships as mentioned in https://github.com/opencivicdata/pupa/issues/303#issuecomment-358778411.
=> Default to resolving memberships by start date, fall back to end date

pupa/cli/commands/clean.py, pupa/tests/clean/test_clean.py
This PR adds a failsafe to the `pupa clean` CLI command. If the command is run with the `--noinput` flag and it finds more than 10 stale items, it will exit with an error. 
Closes #346
=> Add failsafe to clean command

pupa/cli/commands/clean.py, pupa/tests/clean/test_clean.py
This PR adds logging to the `pupa clean` CLI command. When the failsafe is triggered, we'll also output the stale database objects that were found.
=> Add logging to pupa clean failsafe

pupa/cli/commands/clean.py, pupa/tests/clean/test_clean.py
This PR tightens up the `pupa clean` command, by removing the redundant `--noinput` option and editing down logging. It also adds an option to configure the failsafe limit when running the command.
=> Make failsafe configurable and remove redundant option
