pupa/cli/commands/update.py
pupa/importers/base.py
pupa/importers/votes.py

some of this was just pyflakes, but 06554e3 is a fix for displaying kwargs to a scraper.  you're returning a dict, so the code should be calling `.items()`

mostly formatting, but one fix for reporting

---

pupa/scrape/bill.py

new method for adding sponsor by identifier

---

pupa/importers/posts.py
pupa/scrape/popolo.py
pupa/tests/importers/test_post_importer.py
pupa/tests/scrape/test_people_org_scrape.py

I have, for example, a Regional Councillor and a City Councillor representing the same district.

Disambiguate post on role if present

---

pupa/cli/commands/init.py

switched jurisdictions for divisions, added organizations, commented lots, checked division id before saving anything.

init produces usable scraper base

---

pupa/exceptions.py

sorry, can't help myself sometimes

resolve typo-induced anxiety

---

pupa/scrape/event.py
pupa/tests/scrape/test_event_scrape.py

As per http://docs.opencivicdata.org/en/latest/proposals/0004.html#location

forgot url in this method

---

pupa/importers/bills.py

Importer for org sponsors should be the org_importer

---

pupa/scrape/schemas/common.py

The parens in other_names were misplaced.

Misplaced parens in other_names

---

pupa/importers/base.py

This will hopefully make it simpler for folks encountering this error to
determine what might be unexpectedly in the database.

Added ambiguously resolved ids to pseudo-id error.

---

pupa/scrape/schemas/common.py
pupa/tests/importers/test_post_importer.py
pupa/tests/scrape/test_people_org_scrape.py

Allow for datetimes everywhere we allow fuzzy datetimes

---

pupa/cli/commands/update.py
pupa/importers/events.py
pupa/importers/vote_events.py
pupa/scrape/event.py
pupa/tests/importers/test_event_importer.py

Resolve bills, people, and orgs related to agenda events

---

pupa/scrape/popolo.py
pupa/tests/importers/test_membership_importer.py

@jpmckinney here's what was in #220 but squashed.

allow for add_terms to specify organization name

---

pupa/importers/base.py
pupa/tests/importers/test_bill_importer.py

This will close #226 
attn @jamesturk, @jpmckinney

if related fields of objects are updated, update parent object

---

pupa/importers/people.py
pupa/tests/importers/test_people_importer.py

Handle a new person with the same name appearing in the source data

---

pupa/importers/memberships.py
pupa/tests/importers/test_membership_importer.py

Allow member to hold multiple posts in a body

---

CHANGELOG.md
pupa/scrape/popolo.py

This PR allows for the resolution of posts that do not have districts. Sorry for the slow slicing.

handle posts without districts

---

pupa/importers/events.py
pupa/importers/vote_events.py

Allows for resolution of bills that have identifiers modified by fix_bill_ids

consistent use of fix_bill_ids for bill resolution

---

pupa/cli/__main__.py
pupa/cli/commands/migrate.py

This adds a way to update an existing opencivicdata database through pupa.

add migrate command

---

.travis.yml

Django 1.9.10 is https://www.youtube.com/watch?v=lt6PVVr4B04

Install django by version ranges.

---

pupa/cli/commands/update.py

Not sure if this wording is perfect, but IMO it's clearer than before.

Better error on missing sessions.

---

pupa/settings.py

typo in INSTALLED_APPS

---

CHANGELOG.md
pupa/exceptions.py
pupa/importers/organizations.py
pupa/tests/importers/test_event_importer.py
pupa/tests/importers/test_organization_importer.py

orgs with multiple names

---

CHANGELOG.md
pupa/cli/__main__.py
pupa/cli/commands/party.py
pupa/scrape/jurisdiction.py

as discussed in #117, helps solve #118 deadlock
this also adds a warning encouraging users to remove parties from Jurisdiction, will wait for a major release to drop support

New party command

---

pupa/cli/commands/update.py
pupa/scrape/base.py
pupa/settings.py

Goes with https://github.com/jamesturk/scrapelib/pull/37.

Optionally configure tls verification per scraper.

---

pupa/scrape/schemas/person.py

This allows scraping of attributes that have long existing on the
Person OCD model

add family_name and given_name to person schema

---

pupa/scrape/event.py

somehow this did not get added to the previous PR

set location to None if no location_name in args

---

CHANGELOG.md
pupa/__init__.py

This PR bumps the module version and updates the CHANGELOG in preparation for a new release.

Prepare for 0.10.2 release

---

.github/workflows/package.yml
CHANGELOG.md
pupa/__init__.py
setup.py

This PR bumps the module version and updates the CHANGELOG in preparation for a new release.
Closes #346

Prepare for 0.11.0 release
